- name: Get Proxmox version
  ansible.builtin.command: pveversion
  register: proxmox_pveversion_info
  changed_when: false
  ignore_errors: true

- name: Extract Proxmox major version
  ansible.builtin.set_fact:
    proxmox_pve_major: "{{ proxmox_pveversion_info.stdout.split('/')[1].split('.')[0] | int }}"

- name: Install monitoring and frequency utilities
  ansible.builtin.apt:
    name:
      - cpufrequtils
      - ipmitool
      - fio
    state: present
    update_cache: true

- name: Install ipmitool
  ansible.builtin.apt:
    name:
      - ipmitool
    state: present
    update_cache: true
  when: ansible_facts.virtualization_role != 'guest'

- name: Install monitoring and frequency utilities on systems 8+ pve
  ansible.builtin.apt:
    name:
      - proxmox-secure-boot-support
    state: present
    update_cache: true
  when: "(proxmox_pve_major | int) >= 8"

- name: Check CPU vendor
  ansible.builtin.command: cat /proc/cpuinfo
  register: cpu_info
  changed_when: false

- name: Install intel-microcode
  ansible.builtin.apt:
    name: intel-microcode
    state: present
    update_cache: true
  when:
    - "'GenuineIntel' in cpu_info.stdout"
    - "(proxmox_pve_major | int) >= 8"

- name: Install amd64-microcode
  ansible.builtin.apt:
    name: amd64-microcode
    state: present
    update_cache: true
  when:
    - "'AuthenticAMD' in cpu_info.stdout"
    - "(proxmox_pve_major | int) >= 8"

- name: Install sysbench and stress-ng
  ansible.builtin.apt:
    name:
      - sysbench
      - stress-ng
    state: present
    update_cache: true
  when: install_stresstest_software | default(false)

- name: Install packages
  ansible.builtin.command: >
    apt-get install -y {{ install_packages }}
  when: install_packages | default('') | length > 0

- name: Uninstall packages
  ansible.builtin.command: >
    apt-get purge -y {{ uninstall_packages }}
  when: uninstall_packages | default('') | length > 0
