- name: Install monitoring and frequency utilities
  ansible.builtin.apt:
    name:
      - cpufrequtils
      - fio
    state: present
    update_cache: true

- name: Install ipmitool
  ansible.builtin.apt:
    name:
      - ipmitool
    state: present
    update_cache: true
  when: ansible_facts.virtualization_role != 'guest'

- name: Install monitoring and frequency utilities on systems 8+ pve
  ansible.builtin.apt:
    name:
      - proxmox-secure-boot-support
    state: present
    update_cache: true
  when: "(proxmox_pve_major | int) >= 8"

- name: Install intel-microcode
  ansible.builtin.apt:
    name: intel-microcode
    state: present
    update_cache: true
  when:
    - "'GenuineIntel' in global_cpu_vendor"
    - "(proxmox_pve_major | int) >= 8"

- name: Install amd64-microcode
  ansible.builtin.apt:
    name: amd64-microcode
    state: present
    update_cache: true
  when:
    - "'AuthenticAMD' in global_cpu_vendor"
    - "(proxmox_pve_major | int) >= 8"

- name: Install sysbench and stress-ng
  ansible.builtin.apt:
    name:
      - sysbench
      - stress-ng
    state: present
    update_cache: true
  when: install_stresstest_software | default(false)

- name: Install packages
  ansible.builtin.command: >
    apt-get install -y {{ install_packages }}
  when: install_packages | default('') | length > 0

- name: Uninstall packages
  ansible.builtin.command: >
    apt-get purge -y {{ uninstall_packages }}
  when: uninstall_packages | default('') | length > 0
